name: CI for Angular
on: push
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 22.x
        uses: actions/setup-node@v2
        with:
          node-version: 22.x
      - name: Create environment.ts
        run: |
          mkdir -p src/environments
          echo "export const environment = {" > src/environments/environment.ts
          echo "  production: false," >> src/environments/environment.ts
          echo "  API_URL: 'http://api.escuelajs.co'," >> src/environments/environment.ts
          echo "};" >> src/environments/environment.ts
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test --no-watch --no-progress --browsers=ChromeHeadlessCI --code-coverage
