name: CI for Angular
on: push
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 22.x
        uses: actions/setup-node@v2
        with:
          node-version: 22.x
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: ng test --no-watch --no-progress --browsers=ChromeHeadlessCI --code-coverage
